WIP: Add ui module retrival from config
elixir-crawly/crawly pull request #162
Opened 2020-12-22 09:04 UTC by FrancescoZ

Add a new config to notify a different module when an Item is created.

The pipeline still using CrawlyUI as a default value if the configuration is not set

This resolve #152

2020-12-22 09:06 UTC, FrancescoZ commented
@oltarasenko Not sure how I should test this. I cannot us `meck` module to test the call, any suggestion?

2020-12-22 15:13 UTC, Ziinc requested changes
Add in a test for the `:rpc` call.

You can use `:meck` to mock the `:rpc` module, then check the args that was passed to verify that it was called with your given ui module.

2020-12-22 15:13 UTC, Ziinc commented on lib/crawly/pipelines/experimental/send_to_ui.ex
> +    ui_module =
You can make it more concise with `Keyword.get(opts, :ui_module, CrawlyUI)`

2020-12-22 15:19 UTC, Ziinc commented
@FrancescoZ  is `:rpc` [one of the erlang modules that cannot be mocked](https://github.com/eproxus/meck#caveats)?

One way to test this (that i can think of) is to send it to itself, then have a mocked module passed as the ui_module where you can then verify that `store_item` was called.

2020-12-22 19:53 UTC, oltarasenko commented
Looks good to me. If it's possible to add a test that tries to send an rpc call to itself, it could be beneficial. (Otherwise, I would not try to mock RPC).

2020-12-29 11:09 UTC, oltarasenko commented
@FrancescoZ I still have a bit of development time in my timeslot. Should I take over this task? (In case if you're stuck with other things)

2021-03-06 02:37 UTC, Ziinc approved these changes

2021-09-08 21:00 UTC, oltarasenko commented
I have decided to abandon the CrawlyUI project for now. I don't have any spare time to maintain both projects, so I think this one is not a valid thing anyway.

2021-09-08 21:00 UTC, closed without merging