Adding the original request to the parse_item callback
elixir-crawly/crawly pull request #220
Opened 2022-09-14 06:59 UTC by nuno84

Based on the discussion I opened: [discussion](https://github.com/elixir-crawly/crawly/discussions/215)
So, I want to crawl, lets say 100 websites and set the item parse elements (floki query elements) set on a webpage for the user to fine-tune. I found this Oleg article usefull: [article](https://oltarasenko.medium.com/using-elixir-and-crawly-for-price-monitoring-7364d345fc64) 
So my idea is to write a generic HTTP spider and inside it, use that info to parse the data based on the request custom_data.
I think this pull is usefull. And I tried to make it backward compatible.
So now you can do both:

`def parse_item(response), do: ...`
OR
`def parse_item(response, request = %Crawly.Request{custom_data: req_data}), do: ...`

The apply function is now:

```
  defp do_parse(nil, spider_name, response, request) do
    if :erlang.function_exported(spider_name, :parse_item, 2) do
      spider_name.parse_item(response, request)
    else
      spider_name.parse_item(response) # This is for backward compatibility
    end
  end
```

The tests are passing on my computer.
Please take a look.
I can add some documentation if this idea goes forward.
Thank you

2022-11-24 19:14 UTC, starcraft66 commented
Super cool to see this, I was just about to go implement this myself after having a use-case for it (crawling image files for which the metadata is located on the previously-crawled page). I will see how well this works for me and take a look at the failing tests too. Unfortunate that development seems to be stalled on this project.

2022-11-26 18:05 UTC, Ziinc commented
@nuno84 PR is appreciated. The entire `Request` gets copied to the `Response` struct, so adding in the second argument to `parse_item` callback is unnecessary. 

I would suggest using the `metadata` or `meta` key on the `Request` struct instead of `custom_data`, which is more semantically correct.

2022-11-26 18:10 UTC, Ziinc requested changes
please also perform formatting and add in docs on `metadata` usage for creating custom `Request` structs, and accessing them from the `parse_item/1` callback from the `request.metadata` path.

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly.ex
> +               Crawly.Worker.parse_item({response, opts[:with], request}),
see comment

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly/request.ex
> +            custom_data: %{}
`metadata`

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly/request.ex
> +          custom_data: %{}
`metadata`

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly/spider.ex
> +              request :: Crawly.Request.t()
please rm

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly/worker.ex
> +  defp do_parse(nil, spider_name, response, request) do
see comment

2022-11-26 18:10 UTC, Ziinc commented on lib/crawly/worker.ex
> +      fn req ->
variable name change unnecessary, fully qualified names preferred for consistency.

2023-02-02 16:29 UTC, starcraft66 commented
> The entire Request gets copied to the Response struct

@Ziinc The `HTTPoison.Response.t()` contains the original `HTTPoison.Request.t()` struct but I don't think it is helpful in the context of the PR because that `HTTPoison.Request.t()` will not contain any of the metadata stored in the `Crawly.Request.t()` wrapping the response.

2024-04-09 10:18 UTC, closed without merging