Take the RobotsTxt User-Agent from the Request
elixir-crawly/crawly pull request #294
Opened 2024-04-11 07:36 UTC by adonig

This pull request updates the RobotsTxt middleware to dynamically use the User-Agent from each request instead of relying on a hardcoded value. It supersedes an earlier attempt, ensuring that the changes merge cleanly without the previous issues.

2024-04-15 07:46 UTC, adonig commented
Maybe there's a way to squash all those commits into one 😅

2024-04-24 13:26 UTC, oltarasenko requested changes
Could I ask you to add a test to the code, so I can merge it.

2024-04-25 11:01 UTC, adonig commented
Do you believe this test is sufficient?

```elixir
  test "Respects the User-Agent header when evaluating robots.txt" do
    :meck.expect(Gollum, :crawlable?, fn
      "My Custom Bot", _url -> :crawlable
      _ua, _url -> :uncrawlable
    end)

    middlewares = [
      {Crawly.Middlewares.UserAgent, user_agents: ["My Custom Bot"]},
      Crawly.Middlewares.RobotsTxt
    ]

    req = @valid
    state = %{spider_name: :test_spider, crawl_id: "123"}

    assert {%Crawly.Request{}, _state} =
             Crawly.Utils.pipe(middlewares, req, state)

    middlewares = [Crawly.Middlewares.RobotsTxt]

    assert {false, _state} = Crawly.Utils.pipe(middlewares, req, state)
  end
```

2024-04-29 19:45 UTC, oltarasenko approved these changes

2024-04-29 19:45 UTC, merged